#!/bin/bash

if pgrep -x hypridle >/dev/null; then
  pkill -x hypridle
  notify-send "Auto-lock" "Disabled"
else
  uwsm-app -- hypridle >/dev/null 2>&1 &
  notify-send "Auto-lock" "Enabled"
fi

# Signal waybar to update indicator (RTMIN+9)
pkill -RTMIN+9 waybar
